@baseUrl = http://localhost:3000

### get player
POST {{baseUrl}}/game/getPlayer
Content-Type: application/json


### set Coal
POST {{baseUrl}}/game/setCoal
Content-Type: application/json

### money per lvl
POST {{baseUrl}}/game/lvlUp
Content-Type: application/json